# Generated by Django 5.1.5 on 2025-03-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Availible to public'),
        ),
    ]
